[project]
name = "pydice"
version = "0.2.2"
description = "CLI dice roll application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.16.0",
]

[project.scripts]
pydice = "pydice.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
